import { Injectable } from "@angular/core";
import { StepperNodes } from "../types/stepper-nodes";
import { Observable } from "rxjs";
@Injectable({ providedIn: 'root' })
export class StepperService {
  getStepperNodes() {
    return [
      {
        id: 'update',
        index:0,
        labelId:'Product details',
        current: 'product_details',
        next: 'availability',
        previous: 'product_details',
        default: 'product_details',
      },
      {
        id: 'availability',
        index:1,
        labelId:'Availability',
        current: 'availability',
        next: 'policy_configuration',
        previous: 'availability',
        default: 'availability',
      },      
      {
        id: 'policy-configuration',
        index:2,
        labelId:'Policy configuration',
        current: 'policy-configuration',
        next: 'coverage-variant',
        previous: 'availability',
        default: 'policy-configuration',
      },
      {
        id: 'coverage-variant',
        index:3,
        labelId:'Coverage variants',
        current: 'coverage-variant',
        next: 'create-coverage-variant',
        previous: 'policy-configuration',
        default: 'coverage-variant',        
      }, 
      {
        id: 'coverage-variant',
        index:0,
        labelId:'Coverage variant details',
        current: 'coverage-variant',
        next: 'create-coverage-variant',
        previous: 'policy-configuration',
        default: 'coverage-variant',
      },
      {
        id: 'coverage-variant',
        index:0,
        labelId:'Coverage variant',
        current: 'coverage-variant',
        next: 'create-coverage-variant',
        previous: 'policy-configuration',
        default: 'coverage-variant',
      },
      {
        id: 'insured-type',
        index:1,
        labelId:'Insured type',
        current: 'coverage-variant',
        next: 'create-coverage-variant',
        previous: 'policy-configuration',
        default: 'coverage-variant',
      },
      {
        id: 'sub-coverage',
        index:2,
        labelId:'Subcoverages',
        current: 'coverage-variant',
        next: 'create-coverage-variant',
        previous: 'policy-configuration',
        default: 'coverage-variant',
      },
      {
        id: 'coverage-variant-level-overview',
        index:3,
        labelId:'Coverage variant levels',
        current: 'coverage-variant',
        next: 'create-coverage-variant',
        previous: 'policy-configuration',
        default: 'coverage-variant',
      },
      {
        id: 'exclusion',
        index:4,
        labelId:'Exclusions',
        current: 'coverage-variant',
        next: 'create-coverage-variant',
        previous: 'policy-configuration',
        default: 'coverage-variant',
      },
      {
        id: 'inclusion',
        index:5,
        labelId:'Inclusions',
        current: 'coverage-variant',
        next: 'create-coverage-variant',
        previous: 'policy-configuration',
        default: 'coverage-variant',
      },
      {
        id: 'product-attributes',
        index:5,
        labelId:'Product attributes',
        current: 'product-attributes',
        next: 'rating-factor',
        previous: 'coverage-variant',
        default: 'availability',
      },
      {
        id: 'rating-factor',
        index:6,
        labelId:'Select rating factors',
        current: 'rating-factor',
        next: 'availability',
        previous: 'availability',
        default: 'availability',
      },
      {
        id: 'rating-factor',
        index:6,
        labelId:'Ratings',
        current: 'rating-factor',
        next: 'availability',
        previous: 'availability',
        default: 'availability',
      },
      {
        id: 'question-mapping',
        index:6,
        labelId:'External mapping',
        current: 'rating-factor',
        next: 'availability',
        previous: 'availability',
        default: 'availability',
      },

      {
        id: 'documents',
        index:7,
        labelId:'Documents',
        current: 'documents',
        next: 'availability',
        previous: 'availability',
        default: 'availability',
      }
    ];
  }
}